accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [

    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login' ),
    path('sair/', views.sairUsuario, name='sair' ),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/uidb64/token/',auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),



    path('', views.home, name='home'),
    path('perfil/', views.perfil, name='perfil'),
    path('alugados/', views.meusLivros, name='alugados'),
    path('livros/', views.livrosPage, name='livros'),
    path('livros/<int:livro_id>', views.livro, name= 'livro'),
    path('pedido/', views.pedidoPage, name='pedido' ),
    path('reservar_livro/<int:livro_id>', views.reservarLivro, name='reservar_livro'),




    path('adm/', views.pagina_inicial_adm, name='adm_home' ),
    path('adm/perfil', views.perfil_adm, name='perfil_adm' ),

    
    # Funcionalidades de Livros
    path('adm/livros', views.livros_adm, name='livros_adm' ),
    path('adm/livros/<int:livro_id>', views.livro_adm, name='livro_adm' ),
    path('alugar_livro/<int:livro_id>', views.alugar_livro, name='alugar_livro' ),
    path('deletar_livro_adm/<int:livro_id>', views.deletar_livro_adm, name='deletar_livro_adm'),
    path('adicionar_edicao_adm/', views.adicionar_edicao_adm, name='adicionar_edicao_adm'),
    path('adm/livros/adicionar_livro_adm', views.adicionar_livro_adm, name='adicionar_livro_adm' ),
    path('editar_livro_adm/<livro_id>', views.editar_livro_adm, name='editar_livro_adm' ),



    # CRUD de Autores
    path('adm/autores', views.autores_adm, name='autores_adm' ),
    path('deletar_autor_adm/<int:autor_id>', views.deletar_autor_adm, name='deletar_autor_adm'),
    path('editar_autor_adm/<autor_id>/', views.editar_autor_adm, name='editar_autor_adm'),

    # CRUD de Generos
    path('adm/generos', views.generos_adm, name='generos_adm' ),
    path('deletar_genero_adm/<int:genero_id>', views.deletar_genero_adm, name='deletar_genero_adm'),
    path('editar_genero_adm/<genero_id>/', views.editar_genero_adm, name='editar_genero_adm'),

    # CRUD de Editoras
    path('adm/editoras', views.editoras_adm, name='editoras_adm' ),
    path('deletar_editora_adm/<int:editora_id>', views.deletar_editora_adm, name='deletar_editora_adm'),
    path('editar_editora_adm/<editora_id>/', views.editar_editora_adm, name='editar_editora_adm'),



    path('adm/alugueis', views.alugueis_adm, name='alugueis_adm' ),
    path('adm/devolucoes', views.devolucoes_adm, name='devolucoes_adm' ),
    path('adm/pedidos', views.pagina_pedidos_adm, name='pedidos_adm' ),
    path('adm/pedidos/<int:pedido_id>', views.pedido_adm, name= 'pedido_adm'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'))

]

crm/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'))

]

accounts/models.py
from django.db import models
from django.conf import settings

User = settings.AUTH_USER_MODEL

# Create your models here.

class Autor(models.Model):
    nome= models.CharField(max_length=50)
    data_nascimento = models.DateField()
    nacionalidade = models.CharField( max_length=50)
    
    def __str__(self):
        return self.nome


class Editora(models.Model):
    nome = models.CharField(max_length=50)
    data_inalguração = models.DateField()
    nacionalidade = models.CharField( max_length=50)
    endereço = models.CharField(max_length=50)
    telefone = models.DecimalField(max_digits=12,  decimal_places=0)

    def __str__(self):
        return self.nome


class Genero(models.Model):
    nome = models.CharField(max_length=50)
    area = models.CharField(max_length=50)

    def __str__(self):
        return self.nome


class Livro(models.Model):
    isbn = models.DecimalField(max_digits=13, decimal_places=0)
    nome = models.CharField(max_length=50)
    data_lançamento = models.DateField()
    cover = models.ImageField(null=True, blank=True, upload_to='images/', max_length=255 )
    fk_autor = models.ManyToManyField(Autor)
    fk_editora = models.ForeignKey(Editora,null=True, blank=True, on_delete= models.SET_NULL)
    tipo = models.CharField(null=True, blank=True, max_length=50)
    genero_fk = models.ManyToManyField(Genero)

    def __str__(self):
        return self.nome


class Estoque(models.Model):
    livro_fk = models.ForeignKey(Livro,null=True, blank=True, on_delete= models.SET_NULL)
    edicao = models.IntegerField()
    reservado = models.BooleanField(default=False)
    alugado = models.BooleanField(default=False)
    fk_user = models.ForeignKey(User, null=True, blank=True, on_delete= models.SET_NULL)



class Aluguel(models.Model):
    estoque_fk = models.ForeignKey(Estoque, null=True, blank=True, on_delete= models.SET_NULL)
    user_fk = models.ForeignKey(User, null=True, blank=True, on_delete= models.SET_NULL)
    data_alugada = models.DateField()
    dias_alugados = models.IntegerField()
    prazo_devolucao = models.DateField()


class Devolucao(models.Model):
    estoque_fk = models.ForeignKey(Estoque, null=True, blank=True, on_delete= models.SET_NULL)
    user_fk = models.ForeignKey(User, null=True, blank=True, on_delete= models.SET_NULL)
    data_devolucao = models.DateField()


class Mensagem(models.Model):
    user_fk = models.ForeignKey(User,null=True, blank=True, on_delete= models.SET_NULL)
    descricao = models.TextField()
    arquivo = models.FileField(null=True, blank=True, upload_to='docs/')


class Pedido(models.Model):
    user_fk = models.ForeignKey(User,null=True, blank=True, on_delete= models.SET_NULL)
    nome_livro = models.CharField(max_length=50)
    autor = models.CharField(max_length=50)
    tipo = models.CharField(max_length=50)
    genero = models.CharField(max_length=200)
    descricao_pedido = models.TextField()

accounts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import UpdateView
from django.http import Http404, JsonResponse, HttpResponse
from django.contrib import messages
from django.template.loader import render_to_string
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from .forms import CriarUsuarioForm, PedidoForm, EditarUsuarioForm, AdicionarLivroAdm, RegistrarAluguel, AdicionarAutorAdm, DevolucaoForm, AluguelForm, AdicionarGeneroAdm, AdicionarEditoraAdm
from .models import Livro, Pedido, Autor, Genero, Estoque, Aluguel, Devolucao, Editora
from datetime import datetime, timedelta
from django.db.models import Count


# Create your views here.




# ============================================   ADM   ===========================================

#  Pagina Inicial do ADM
@login_required(login_url='login')
@staff_member_required
def pagina_inicial_adm(request):
    dataset = Livro.objects.values('tipo').annotate(total=Count('tipo')).order_by('tipo')
    tipos = [data['tipo'] for data in dataset]
    totais = [data['total'] for data in dataset]

    autores_dataset = Autor.objects.annotate(total_books=Count('livro')).order_by('nome')
    autores = [autor.nome for autor in autores_dataset]
    livros_por_autor = [autor.total_books for autor in autores_dataset]

    context = {
        'tipos': tipos,
        'totais': totais,
        'autores': autores,
        'livros_por_autor': livros_por_autor,
    }

    return render(request, 'accounts/adm/pagina_inicial_adm.html', context)


@login_required(login_url='login')
@staff_member_required
def perfil_adm(request):
    user = request.user
    if request.method == 'POST':
        user_form = EditarUsuarioForm(request.POST, instance=request.user)

        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Usuario Atualizado com Sucesso')
            return redirect(to='perfil')
    else:
        user_form = EditarUsuarioForm(instance=request.user)

    return render(request, 'accounts/adm/perfil_adm.html', {'user_form': user_form})



# ADM  Pedido
@login_required(login_url='login')
@staff_member_required
def pagina_pedidos_adm(request):
    pedidos = Pedido.objects.all()
    return render(request,'accounts/adm/pedidos_adm.html', {'pedidos': pedidos})

@login_required(login_url='login')
@staff_member_required
def pedido_adm(request, pedido_id):
    pedido = Pedido.objects.get(pk=pedido_id)
    if pedido is not None:
        return render(request, 'accounts/adm/pedido_adm.html', {'pedido': pedido})
    else:
        raise Http404("Pedido NAO Existe")
    




# ADM  Livro

@login_required(login_url='login')
@staff_member_required
def livros_adm(request):
    livros = Livro.objects.prefetch_related('fk_autor')
    autores = Autor.objects.all()
    query = request.GET.get('q')
    if query:
        livros = livros.filter(nome__icontains=query)

    autor_id = request.GET.get('autor')
    if autor_id:
        livros = livros.filter(fk_autor__id=autor_id)
    
    return render(request,'accounts/adm/livros_crud/livros_adm.html', {'livros': livros , 'autores': autores})

@login_required(login_url='login')
@staff_member_required
def livro_adm(request, livro_id):
    copia_disponivel = Estoque.objects.filter(livro_fk = livro_id, reservado=False, alugado=False).exists()
    livro = Livro.objects.get(pk=livro_id)
    autores = livro.fk_autor.all()
    generos = livro.genero_fk.all()
    if livro is not None:
        return render(request, 'accounts/adm/livros_crud/livro_adm.html', {'livro': livro, 'autores': autores, 'generos': generos, 'copia_disponivel':copia_disponivel})
    else:
        raise Http404("Livro NAO Existe")


@login_required(login_url='login')
@staff_member_required
def alugar_livro(request, livro_id):
    estoque_disponivel = Estoque.objects.filter(livro_fk=livro_id, reservado=False, alugado=False).order_by('id').first()
    if estoque_disponivel:
        if request.method == 'POST':
            form = AluguelForm(request.POST)
            if form.is_valid():
                aluguel = form.save(commit=False)
                aluguel.estoque_fk = estoque_disponivel
                aluguel.data_alugada = datetime.now()
                dias_alugados = aluguel.dias_alugados
                prazo_devolucao = datetime.now() + timedelta(days=dias_alugados)
                aluguel.prazo_devolucao = prazo_devolucao
                aluguel.save()

                estoque_pk = aluguel.estoque_fk.id
                estoque = Estoque.objects.get(pk=estoque_pk)
                estoque.fk_user = aluguel.user_fk
                estoque.alugado = True
                estoque.save()
                return redirect('livro_adm', livro_id=livro_id)
        else:
            form = AluguelForm()
        return render(request, 'accounts/adm/aluguel_adm.html', {'form': form})
    else:
        return redirect('livro_adm',livro_id=livro_id)
    


@login_required(login_url='login')
@staff_member_required
def deletar_livro_adm(request, livro_id):
    livro = Livro.objects.get(pk=livro_id)
    livro.delete()
    messages.success(request, 'Livro Deletado com Sucesso ')
    return redirect('livros_adm')

@login_required(login_url='login')
@staff_member_required
def adicionar_livro_adm(request):
    if request.method == 'POST':
        form = AdicionarLivroAdm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Livro Adicionado com Sucesso ')
            return redirect('adicionar_livro_adm')
    else:
        form = AdicionarLivroAdm()

    return render(request, 'accounts/adm/livros_crud/adicionar_livro_adm.html', {'form':form})


def editar_livro_adm(request, livro_id):
    livro = Livro.objects.get(pk=livro_id)
    if request.method == 'POST':
        form = AdicionarLivroAdm(request.POST, instance=livro)
        if form.is_valid():
            form.save()
            messages.success(request, 'Livro Editado com Sucesso ')
            return redirect('editar_livro_adm', livro.pk)
    else:
        form = AdicionarLivroAdm(instance=livro)
    return render(request, 'accounts/adm/livros_crud/editar_livro_adm.html', {'form': form})


@login_required(login_url='login')
@staff_member_required
def adicionar_edicao_adm(request):
    if request.method == 'POST':
        livro_id = request.POST.get('livro_id')
        num_copias = int(request.POST.get('num_copias'))
        livro = Livro.objects.get(pk=livro_id)

        maior_edicao = Estoque.objects.filter(livro_fk = livro).order_by('-edicao').first()
        if maior_edicao:
            proxima_edicao = maior_edicao.edicao + 1
        else:
            proxima_edicao = 1

        for i in range(proxima_edicao, proxima_edicao + num_copias):
            estoque = Estoque(livro_fk = livro, edicao=i)
            estoque.save()
        return redirect('livro_adm', livro_id=livro_id)
    else:
        return redirect('livro_adm')
    









# ADM  AUTOR

@login_required(login_url='login')
@staff_member_required
def autores_adm(request):
    autores = Autor.objects.all()

    if request.method == 'POST':
        form = AdicionarAutorAdm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Autor Adicionado com Sucesso ')
            return redirect('autores_adm')
    else:
        form = AdicionarAutorAdm()
        
    return render(request,'accounts/adm/autores_crud/autores_adm.html', {"autores": autores, 'form':form})


@login_required(login_url='login')
@staff_member_required
def deletar_autor_adm(request, autor_id):
    autor = Autor.objects.get(pk=autor_id)
    autor.delete()
    messages.success(request, 'Autor Deletado com Sucesso ')
    return redirect('autores_adm')



def editar_autor_adm(request, autor_id):
    autor = Autor.objects.get(pk=autor_id)
    if request.method == 'POST':
        form = AdicionarAutorAdm(request.POST, instance=autor)
        form.save()
        messages.success(request, 'Livro Editado com Sucesso ')
        return redirect('editar_autor_adm', autor.pk)
    else:
        form = AdicionarAutorAdm(instance=autor)
    return render(request, 'accounts/adm/autores_crud/editar_autor_adm.html', {'form': form})











# ADM  ALUGUEL

@login_required(login_url='login')
@staff_member_required
def alugueis_adm(request):
    if request.method == 'POST':
        form = RegistrarAluguel(request.POST)
        if form.is_valid():
            aluguel = form.save(commit=False)

            estoque_pk = aluguel.estoque_fk.id
            estoque = Estoque.objects.get(pk=estoque_pk)
            if estoque.reservado == False and estoque.alugado == False:

                estoque.fk_user = aluguel.user_fk
                estoque.alugado = True
                estoque.save()

                dias_alugados = aluguel.dias_alugados
                prazo_devolucao = datetime.now() + timedelta(days=dias_alugados)
                aluguel.prazo_devolucao = prazo_devolucao
                aluguel.data_alugada = datetime.now()
                form.save()
                messages.success(request, 'Livro Alugado com Successo')
                return redirect('alugueis_adm')
            else:
                messages.error(request, 'Livro Indisponivel para Aluguel')
                
            return redirect('alugueis_adm')
                
    else:
        form = RegistrarAluguel()

    alugueis = Aluguel.objects.all()


    return render(request,'accounts/adm/alugueis_adm.html', {'form': form, 'alugueis':alugueis})












# ADM  DEVOLUÇÕES

@login_required(login_url='login')
@staff_member_required
def devolucoes_adm(request):
    if request.method == 'POST':
        form = DevolucaoForm(request.POST)
        if form.is_valid():
            form.save()

accounts/templates/accounts/dashboard.html
{% extends "accounts/test.html" %}

{%load static %}

{% block styles %}
<link rel="stylesheet" href="{%static 'accounts/css/home.css'%}">
{% endblock %}


{% block content %}

<div class="container">
    <div class="left-div">
        <img src="{% static 'accounts/img/home-page-image.png'%}" alt="Imagem">
    </div>
    <div class="right-div">
        <div>
            <center>
            <h1>Bem Vindo ao</h1>
            <h1>Cyber Books</h1>
            <br>
            <a href="{% url 'livros'%}"><button type="button" class="btn btn-light">Buscar Livros</button><a/>
            </center>
        </div>
    </div>
</div>

{% endblock content %}

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{%static 'accounts/css/register.css'%}">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    </style>
</head>

<body>

    <div class="pagina">
        <div class="div1">
            <img id='imagem' src="{% static 'accounts/img/Library-rafiki.png'%}">
        </div>
        <div class="div2">
            {% include "accounts/components/login_form.html" %}
        </div>
    </div>

</body>
</html>

accounts/templates/accounts/pedido.html
{% extends "accounts/test.html" %}

{%load static %}

{% block styles %}
<link rel="stylesheet" href="{%static 'accounts/css/pedido.css'%}">
{% endblock %}

{% block content %}


<div class='container'>

    <center>
        <br/>
        <h1>Fazer Solicitação de Livro</h1>
        <br/>
    </center>
    


    <form method="post">

        {% csrf_token %}

        <div class="row">

            <div class='col'>
                <div class="form-group">
                    <label for="id_nome_livro">Nome do Livro</label>
                    <input type="text" class="form-control" id="id_nome_livro" name="nome_livro" placeholder="Nome do Livro">
                </div>
            </div>

            <br/>
            
            <div class='col'>
                <div class="form-group">
                    <label for="id_autor">Autor</label>
                    <input type="text" class="form-control" id="id_autor" name="autor" placeholder="Autor">
                </div>
            </div>

        </div>

        <br/>

        <div class="row">

            <div class='col'> 
                <div class="form-group">
                    <label for="id_tipo">Tipo</label>
                    <select class="form-control" id="id_tipo" name="tipo">
                        <option value="Ficçao">Ficção</option>
                        <option value="Não Ficção">Nao Ficção</option>
                    </select>
                </div>
            </div>

            <div class='col'> 
                <div class="form-group">
                    <label for="id_genero">Genero</label>
                    <input type="text" class="form-control" id="id_genero" name="genero" placeholder="Genero">
                </div>
            </div>

        </div>

        <br/>
        
        <div class="form-group">
            <label for="id_descricao">Descrição</label>
            <textarea type="textarea" class="form-control" id="id_descricao" name="descricao_pedido" placeholder="Descição do Pedido"></textarea>
        </div>

        <br/>
        

        <center>

            <button type="submit" class="btn btn-primary">Solicitar</button>

    
            {% for message in messages %}
                <p id='messages'>{{message}}</p>
            {% endfor %}

        </center>

    </form>

</div>



{% endblock %}

accounts/templates/accounts/register.html
{% load static%}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{%static 'accounts/css/register.css'%}">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>
<body>

    <div class="pagina">
        <div class="div1">
            <img id='imagem' src="{% static 'accounts/img/Library-rafiki.png'%}">
        </div>
        <div class="div2">
            {% include "accounts/components/register_form.html" %}
        </div>
    </div>

</body>
</html>

accounts/templates/accounts/test.html
{%load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>{% block title %}{% endblock %}</title>
  {% block styles%}{%endblock%}
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'accounts/css/base.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'fa/favicon.png' %}" >
  
</head>
<body>
    
  {% include "accounts/components/navbar.html" %}

  {% block content %}
  {% endblock %}
  
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>


</body>
</html>